In [1]:
# number of instances
m = 6
# number of urns for each instance
k_lis = [2,2,2,3,3,3]
# the prior probability of each urn being chosen for each instance
# will be equal prob for now
prior_lis = [1/k for k in k_lis]
# the number of ball colours that each urn contains for each instance
j_lis = [2,3,4,2,3,4]
# Experimental Design: Ball compositions and define the maximum number of urns = 3 and maximum number of colours = 4
ball_comp = {(2,2):{'p_col1_u1':0.8, 'p_col2_u1':0.2, 'p_col1_u2':0.2, 'p_col2_u2':0.8}, 
             (2,3):{'p_col1_u1':0.7, 'p_col2_u1':0.2, 'p_col3_u1':0.1, 'p_col1_u2':0.2, 'p_col2_u2':0.1, 'p_col3_u2':0.7},
             (2,4):{'p_col1_u1':0.4, 'p_col2_u1':0.3, 'p_col3_u1':0.2, 'p_col4_u1':0.1, 'p_col1_u2':0.1, 'p_col2_u2':0.2, 'p_col3_u2':0.3, 'p_col4_u2':0.4},
             (3,2):{'p_col1_u1':0.8, 'p_col2_u1':0.2, 'p_col1_u2':0.5, 'p_col2_u2':0.5, 'p_col1_u3':0.2, 'p_col2_u3':0.8},
             (3,3):{'p_col1_u1':0.7, 'p_col2_u1':0.2, 'p_col3_u1':0.1, 'p_col1_u2':0.4, 'p_col2_u2':0.3, 'p_col3_u2':0.3, 'p_col1_u3':0.2, 'p_col2_u3':0.1, 'p_col3_u3':0.7},
             (3,4):{'p_col1_u1':0.4, 'p_col2_u1':0.3, 'p_col3_u1':0.2, 'p_col4_u1':0.1, 'p_col1_u2':0.25, 'p_col2_u2':0.25, 'p_col3_u2':0.25, 'p_col4_u2':0.25, 'p_col1_u3':0.1, 'p_col2_u3':0.2, 'p_col3_u3':0.3, 'p_col4_u3':0.4}
}

In [2]:
import numpy as np

def simulate_ball_draws( k, j, n, ball_comp):
    """
    Simulate a sequence of ball draws.

    Parameters:
        n (int): Length of the sequence.
        ball composition: a dict of dict. keys of first dict is number of urns and number of colours, the second key is p_colj_uk
        total number of urns k, 
        total number of colours j,

    Returns:
        list: Simulated sequence of ball draws.
    """

    # generate urn number list
    urns = np.arange(1,k+1)
    # generate colour list
    colors = np.arange(1,j+1)

    # randomly choose a urn to draw n balls with replacement
    chosen_urn = np.random.choice(urns)

    # grab relevant experimental design base on k and j
    probabilities_dict = ball_comp[(k, j)]
    # get probability list for np.random.choice from experiment design
    # first element is p_col1_chosenUrn, p_col2_chosenUrn...
    probabilities = []
    for col in range(1,j+1):
        probabilities.append(probabilities_dict[f"p_col{col}_u{chosen_urn}"])
    return (chosen_urn, np.random.choice(colors, size=n, p=probabilities))

sequence = simulate_ball_draws(k=3,j=2, n=4, ball_comp=ball_comp)
print(sequence)

(3, array([2, 2, 2, 2]))


In [3]:
# assume 4 ball draws per instance
n = 4
chosen_urn_lis = []
ball_draw_lis = []
for instance in range(m):
    chosen_urn, sequence = simulate_ball_draws(k=k_lis[instance],j=j_lis[instance],n=n,ball_comp=ball_comp)
    chosen_urn_lis.append(chosen_urn)
    ball_draw_lis.append(sequence)

In [4]:
display(chosen_urn_lis)
display(ball_draw_lis)

[2, 1, 2, 3, 1, 1]

[array([2, 1, 1, 2]),
 array([1, 2, 1, 1]),
 array([3, 1, 4, 4]),
 array([2, 1, 2, 2]),
 array([1, 1, 1, 1]),
 array([2, 2, 2, 4])]

In [5]:
input_variable_lis = []
for instance in range(m):
    input_variable_lis.append((f"BU{instance+1}_chosenUrn",chosen_urn_lis[instance]))
    input_variable_lis.append((f"BU{instance+1}_ballDraws",ball_draw_lis[instance]))
    for urn in range(k_lis[instance]):
        input_variable_lis.append((f"BU{instance+1}_urn{urn+1}_prior",prior_lis[instance]))
        for col in range(j_lis[instance]):
            input_variable_lis.append((f"BU{instance+1}_urn{urn+1}_col{col+1}", ball_comp[(k_lis[instance],j_lis[instance])][f"p_col{col+1}_u{urn+1}"]*10))
print(len(input_variable_lis))
input_variable_lis

72


[('BU1_chosenUrn', 2),
 ('BU1_ballDraws', array([2, 1, 1, 2])),
 ('BU1_urn1_prior', 0.5),
 ('BU1_urn1_col1', 8.0),
 ('BU1_urn1_col2', 2.0),
 ('BU1_urn2_prior', 0.5),
 ('BU1_urn2_col1', 2.0),
 ('BU1_urn2_col2', 8.0),
 ('BU2_chosenUrn', 1),
 ('BU2_ballDraws', array([1, 2, 1, 1])),
 ('BU2_urn1_prior', 0.5),
 ('BU2_urn1_col1', 7.0),
 ('BU2_urn1_col2', 2.0),
 ('BU2_urn1_col3', 1.0),
 ('BU2_urn2_prior', 0.5),
 ('BU2_urn2_col1', 2.0),
 ('BU2_urn2_col2', 1.0),
 ('BU2_urn2_col3', 7.0),
 ('BU3_chosenUrn', 2),
 ('BU3_ballDraws', array([3, 1, 4, 4])),
 ('BU3_urn1_prior', 0.5),
 ('BU3_urn1_col1', 4.0),
 ('BU3_urn1_col2', 3.0),
 ('BU3_urn1_col3', 2.0),
 ('BU3_urn1_col4', 1.0),
 ('BU3_urn2_prior', 0.5),
 ('BU3_urn2_col1', 1.0),
 ('BU3_urn2_col2', 2.0),
 ('BU3_urn2_col3', 3.0),
 ('BU3_urn2_col4', 4.0),
 ('BU4_chosenUrn', 3),
 ('BU4_ballDraws', array([2, 1, 2, 2])),
 ('BU4_urn1_prior', 0.3333333333333333),
 ('BU4_urn1_col1', 8.0),
 ('BU4_urn1_col2', 2.0),
 ('BU4_urn2_prior', 0.3333333333333333),
 ('BU4

In [8]:
output_variable_lis = []
for instance in range(m):
    for ball_draw in range(len(ball_draw_lis[instance])):
        for urn in range(k_lis[instance]):
            output_variable_lis.append((f"BU{instance+1}_draw{ball_draw+1}_urn{urn+1}_posterior", "Prob_Here"))
        
        output_variable_lis.append((f"BU{instance+1}_draw{ball_draw+1}_repUrn", "Urn Name"))

        for col in range(j_lis[instance]):
            output_variable_lis.append((f"BU{instance+1}_draw{ball_draw+1}_col{col+1}_posterior", "Prob_Here"))
        
        output_variable_lis.append((f"BU{instance+1}_draw{ball_draw+1}_repCol", "Colour Name"))

        output_variable_lis.append((f"BU{instance+1}_draw{ball_draw+1}_time","Time"))

print(len(output_variable_lis))
output_variable_lis       

204


[('BU1_draw1_urn1_posterior', 'Prob_Here'),
 ('BU1_draw1_urn2_posterior', 'Prob_Here'),
 ('BU1_draw1_repUrn', 'Urn Name'),
 ('BU1_draw1_col1_posterior', 'Prob_Here'),
 ('BU1_draw1_col2_posterior', 'Prob_Here'),
 ('BU1_draw1_repCol', 'Colour Name'),
 ('BU1_draw1_time', 'Time'),
 ('BU1_draw2_urn1_posterior', 'Prob_Here'),
 ('BU1_draw2_urn2_posterior', 'Prob_Here'),
 ('BU1_draw2_repUrn', 'Urn Name'),
 ('BU1_draw2_col1_posterior', 'Prob_Here'),
 ('BU1_draw2_col2_posterior', 'Prob_Here'),
 ('BU1_draw2_repCol', 'Colour Name'),
 ('BU1_draw2_time', 'Time'),
 ('BU1_draw3_urn1_posterior', 'Prob_Here'),
 ('BU1_draw3_urn2_posterior', 'Prob_Here'),
 ('BU1_draw3_repUrn', 'Urn Name'),
 ('BU1_draw3_col1_posterior', 'Prob_Here'),
 ('BU1_draw3_col2_posterior', 'Prob_Here'),
 ('BU1_draw3_repCol', 'Colour Name'),
 ('BU1_draw3_time', 'Time'),
 ('BU1_draw4_urn1_posterior', 'Prob_Here'),
 ('BU1_draw4_urn2_posterior', 'Prob_Here'),
 ('BU1_draw4_repUrn', 'Urn Name'),
 ('BU1_draw4_col1_posterior', 'Prob_Here'),

Combine urn1 urn2 posterior, col1 col2 posterior, combine urn 1 urn 2 priors, urn 1 urn 2 colours, add another variable called BU1 colour mapping, combine urn 1 urn 2 urn composition